### ISSUE TITLE
Pasting maxlength data tabs but deletes data in next field

### ISSUE THREAD

**Issue by TronixGT** [Mathachew/jquery-autotab#72]
Whenever I paste data equivalent to maxlength, it tabs to the next field but deletes all data in the next field. 

I saw that you had a few pasting issues already so I tried to upgrade from 1.7 to 1.8.1 and it still occurred. 

Example:  http://jsfiddle.net/B9hJ9/10/

**Comment by Mathachew** [comment]
@TronixGT A month later, and the fix is out. Sorry to it took so long!
