### ISSUE TITLE
Format doesn't handle drag and drop

### ISSUE THREAD

**Issue by patstuart** [Mathachew/jquery-autotab#73]
Dragging and dropping text from elsewhere into the textbox does not trigger the format filter.

I believe this can be fixed by simply adding the `drop` element to the `paste` event handler such that

    }).on('paste', function (e) {

becomes

    }).on('drop paste', function (e) {

. Tested on IE8+, Chrome, and Firefox (if I recall correctly). I am not familiar enough with the pull process to make this change on my own. :)

**Comment by Mathachew** [comment]
I'm a little disappointed in myself for not thinking of that since dragging text into a textbox is something I've done plenty of times in the past. I'll be sure to include this in the next update, which I meant to do last week but got tied up with other things. Thanks!

**Comment by Mathachew** [comment]
@patstuart Drop support has been added, and even works for IE6 and 7.
