### ISSUE TITLE
Feature request: tab upon arrow keys

### ISSUE THREAD

**Issue by patstuart** [Mathachew/jquery-autotab#74]
Could you add arrow key functionality to autotab?
* Move to the previous field when the user types the left arrow on the keyboard and the cursor is on the far left.
* To the next field if the user presses the right arrow and the cursor is on the right edge.

**Comment by Mathachew** [comment]
I'll mull over this one. My gut reaction is that I'll include it.

**Comment by Mathachew** [comment]
@patstuart Support for moving through the fields with the arrow key has been added.
