### ISSUE TITLE
Not work with input type "tel"

### ISSUE THREAD

**Issue by PawelGIX** [Mathachew/jquery-autotab#75]
Not work with input type "tel"

**Comment by Mathachew** [comment]
Tel, like most of the newer input types, do not support text selection for cursor placement, which is critical for the filtering functionality. I'll look into possibly ignoring filtering rules if the type isn't text, password or textarea, but can't make any promises.

**Comment by Mathachew** [comment]
@PawelGIX Limited support for tel, and several other HTML5 input fields, has been added.
