### ISSUE TITLE
Pasting overwrites button text if button is <input> instead of <button>

### ISSUE THREAD

**Issue by bill-uncultured** [Mathachew/jquery-autotab#79]
This was part of bug #65, but that got closed when part of it was fixed. Still happens in 1.9.1, except for the case where the pasted text is the same length as the text fields.

When you paste into autotab input text fields, the text of the following button gets overwritten if:
   -The button is an <input> rather than a <button> (input with type=button, submit, maybe others)
   -The amount pasted is longer than the input text fields. (The excess text becomes the button text.)

1.9.0 fixes the case where the button gets blanked if the amount pasted characters equals the input field lengths.

Sample html code (slightly simplified from bug #65):
(Note that if you switch the order of the <input type="button"> and the <button>, the problem goes away.)
```
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Demo: autotab 1.9.1 overwrites button text</title>
  <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
  <script src="https://raw.githubusercontent.com/Mathachew/jquery-autotab/1.9.1/js/jquery.autotab.min.js"></script>
</head>
<body>
  <form>
    <input class="keyEntry" type="text" maxlength="5" />
    <input class="keyEntry" type="text" maxlength="5" />
    <input value="Submit" type="button" />
    <button type="submit">Submit</button>
  </form>
  <script>
$.autotab({ tabOnSelect: true });
$('.keyEntry').autotab('filter', { format: 'alphanumeric', uppercase: true});
  </script>
</body>
</html>
```

**Comment by bill-uncultured** [comment]
Here's a partial fix:
```
$ diff -u jquery.autotab.1.9.1.js jquery.autotab.1.9.1-bill.js 
--- jquery.autotab.1.9.1.js	2015-02-12 15:39:01.625321085 -0700
+++ jquery.autotab.1.9.1-bill.js	2015-02-12 15:38:26.128220692 -0700
@@ -691,7 +691,7 @@
 
                         var defaults = getSettings(e);
 
-                        if ($(e).prop('disabled') || $(e).prop('readonly')) {
+                        if ($(e).prop('disabled') || $(e).prop('readonly') || $(e).prop('type')=='button') {
                             $(e).trigger('autotab-next');
 
                             if (!settings.iOS) {
@@ -762,4 +762,4 @@
         return $(this).autotab('filter', defaults);
     };
 
-})(jQuery);
\ No newline at end of file
+})(jQuery);
```
But you probably want more cases, like line 543 in jquery.autotab.1.9.1.js:
```
                if (this.type === 'select-one' || this.type === 'select-multiple' || this.type === 'checkbox' || this.type === 'radio' || this.type === 'button' || this.type === 'submit' || this.type === 'range') {
```

**Comment by Mathachew** [comment]
Thanks for the info @bill-uncultured. I have a fix that I wanted to test more thoroughly before creating another release. Should be some time this week.

**Comment by Mathachew** [comment]
@bill-uncultured 1.9.2 is out and should fix this issue.

**Comment by bill-uncultured** [comment]
Fix confirmed. Thanks, Mathachew!
