### ISSUE TITLE
support number input

### ISSUE THREAD

**Issue by owlyowl** [Mathachew/jquery-autotab#83]
Hi I'm running this in angular and it works really well with text inputs.. Change the input type to number and tab backwards and try and replace a selection by typing a new number doesn't replace all the contents it just jumps to the next field

Wondering it there's a fix and why numbers were treated differently in the source?

**Comment by Mathachew** [comment]
Unfortunately this is out of my hands. Like other newer input types, number doesn't support selection functionality. I've detailed the problem in the [Known Issues](https://github.com/Mathachew/jquery-autotab#known-issues) section.

**Comment by owlyowl** [comment]
Thanks for looking in to it Matthew most appreciated.

On 1 April 2015 at 03:56, Matthew Miller notifications@github.com wrote:

> Unfortunately this is out of my hands. Like other newer input types,
> number doesn't support selection functionality. I've detailed the problem
> in the Known Issues
> https://github.com/Mathachew/jquery-autotab#known-issues section.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Mathachew/jquery-autotab/issues/83#issuecomment-88170953
> .

## 

Tom Fulcher
Creative Designer and Developer

[image: Envoy]

Envoy Advanced Technologies Pty Ltd
Level 1, 194 Miller St, North Sydney NSW 2060

Mobile Apps | Software Development | Custom Applications | Fully Managed
Hosting

http://www.envoyat.com | m: 0403 316 714 | p: +61 2 8097 7328 | skype:
thomen12

---

This email and any attachment is only intended for the use of the
individuals or entities to whom it is addressed and may contain
confidential, privileged information. If the reader of this information is
not the addressee, please be advised that any dissemination, distribution
or copying of this email is strictly prohibited. If you receive this
communication in error, please return this email to Envoy Advanced
Technologies at the above email address and delete it from your files.
Thank you.
